version: '3.3'
services:
  database:
    image: mysql:5.7
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'school'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'