spring:
  application:
    name: "registration-course"
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?&useSSL=false
    username: root
    password: password

registration:
  max-students-per-course: 50
  student-can-register-max: 5

server:
  port: 8080