version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: 'school'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
      - './.mysql-data/db:/var/lib/mysql'
    networks:
      - registration-network

  registration:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: registration:1.0
    ports:
      - 8080:8080
    environment:
      WAIT_HOSTS: db:3306
      WAIT_TIMEOUT: 45
      WAIT_AFTER: 10
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/school?autoReconnect=true&useSSL=false
    depends_on:
      - db
    networks:
      - registration-network

networks:
  registration-network:
    driver: bridge

