USE school;

CREATE TABLE STUDENT (ID int NOT NULL AUTO_INCREMENT,LAST_NAME  varchar(50) NOT NULL,FIRST_NAME varchar(50),PRIMARY KEY (ID));
CREATE TABLE COURSE (ID int NOT NULL AUTO_INCREMENT,COURSE_NAME  varchar(500) NOT NULL,PRIMARY KEY (ID));
CREATE TABLE REGISTRATION_COURSE (ID int NOT NULL AUTO_INCREMENT,STUDENT_ID int NOT NULL,COURSE_ID int NOT NULL, FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID) ON UPDATE CASCADE ON DELETE RESTRICT,FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID) ON UPDATE CASCADE ON DELETE RESTRICT, PRIMARY KEY (ID));
