USE school;

CREATE TABLE STUDENT (ID int NOT NULL AUTO_INCREMENT,LAST_NAME  varchar(50) NOT NULL,FIRST_NAME varchar(50),PRIMARY KEY (ID));
CREATE TABLE COURSE (ID int NOT NULL AUTO_INCREMENT,COURSE_NAME  varchar(500) NOT NULL,PRIMARY KEY (ID));
CREATE TABLE REGISTRATION_COURSE (ID int NOT NULL AUTO_INCREMENT,STUDENT_ID int NOT NULL,COURSE_ID int NOT NULL, FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID) ON UPDATE CASCADE ON DELETE RESTRICT,FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID) ON UPDATE CASCADE ON DELETE RESTRICT, PRIMARY KEY (ID));

INSERT INTO STUDENT (FIRST_NAME, LAST_NAME) VALUES('Anne','Bower');
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME) VALUES('Frank','Butler');
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME) VALUES('Gordon','Chapman');
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME) VALUES('Dorothy','Russell');
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME) VALUES('Felicity','Thomson');
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME) VALUES('Irene','Allan');
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME) VALUES('Gavin','Watson');
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME) VALUES('Max','James');
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME) VALUES('Keith','Reid');
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME) VALUES('Karen','Graham');
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME) VALUES('Nathan','Gill');
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME) VALUES('Luke','Ince');
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME) VALUES('Stewart','Wright');
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME) VALUES('David','Hodges');
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME) VALUES('Rebecca','Harris');

INSERT INTO COURSE (COURSE_NAME) VALUES('Wealth and Econometrics in Philosophical Psychology');
INSERT INTO COURSE (COURSE_NAME) VALUES('Psychology, Text, and Justice in the American Imaginary');
INSERT INTO COURSE (COURSE_NAME) VALUES('Logic and Seniors in Politics, Markets, and Society');
INSERT INTO COURSE (COURSE_NAME) VALUES('Drones and Biotechnology in History of Science & Medicine');
INSERT INTO COURSE (COURSE_NAME) VALUES('Service, Video, and Devices in the History of Technology');
INSERT INTO COURSE (COURSE_NAME) VALUES('Probability and Materials in East Asian Literature and Film');
INSERT INTO COURSE (COURSE_NAME) VALUES('Justice, Space, and Rotations');
INSERT INTO COURSE (COURSE_NAME) VALUES('Capitalism and Liberty in Environmental Health');
INSERT INTO COURSE (COURSE_NAME) VALUES('Cybersecurity, Nutrition, and Abstraction');
INSERT INTO COURSE (COURSE_NAME) VALUES('Domesticity, Quebec, and Genders');


SELECT ID FROM STUDENT ORDER BY RAND() LIMIT 1 INTO @SID1;
SELECT ID FROM COURSE ORDER BY RAND() LIMIT 1 INTO @CID1;
INSERT INTO REGISTRATION_COURSE (STUDENT_ID, COURSE_ID) VALUES (@SID1, @CID1);